### PR TITLE
Add example/previews support

### PR DESCRIPTION
**Pull request by mike-sheppard**
**Summary**
Add example/preview support as per - https://www.advancedcustomfields.com/resources/acf_register_block_type/

**Preview**

acf-blocks-example-setting

**Example Block Before**

Screenshot 2020-07-15 at 12 42 55

**Example BlockAfter**

Screenshot 2020-07-15 at 12 43 15

### CODE REVIEW

**Comment by Log1x** [comment]
Nice! I'll merge this with #28 once it's ready.

**Comment by Log1x** [comment]
lol can you resubmit this PR? i got absolutely Pwned by git idk what happened. 😭

**Comment by mike-sheppard** [comment]
haha sure thing! I'll get it over a little later today :)

**Comment by huubl** [comment]
Hi, will this be merged into master?

**Comment by mike-sheppard** [comment]
yup, I'll pop the PR back in again!

**Comment by mike-sheppard** [comment]
Reopened in https://github.com/Log1x/acf-composer/pull/41

**Pull request closed without merging**
