### PR TITLE
Allow the use of user created stubs

### PR DESCRIPTION
**Pull request by mrmadhat**
Allows the user to publish the stubs folder and customize the stubs to their needs. See #103

### CODE REVIEW

**Comment by Log1x** [comment]
Thanks a lot for the PR! I'm on vacation right now but will try to get to reviewing ASAP.

**Comment by mrmadhat** [comment]
Hey @Log1x have you had a chance to take a look at this?

**Comment by Log1x** [comment]
Could you add me to the fork repo so I can push up a few changes before merging this?

**Comment by Log1x** [comment]
Thanks a ton!

**Pull request merged**
