### PR TITLE
Allow subfolders usage

### PR DESCRIPTION
**Pull request by davideprevosto**
My goal was to better organize our multiple Blocks and Fields files into their own NameSpace.

For example:

Blocks
-- Products
---- ProductTypology1.php
---- ProductTypology2.php
-- Portfolio
---- Portfolio1.php

Fields
-- Products
---- Details.php
---- Carousel.php

[...]

### CODE REVIEW

**Comment by davideprevosto** [comment]
@Log1x sorry about that. It seems I have missed some linting.

**Comment by Twansparant** [comment]
Yeah this would be great addition!

**Comment by Log1x** [comment]
Thanks for the PR. I assume you've tested this and it works as intended? No conflict with partials or anything?

Would you be able to fix the remaining linting that happened on the file?

**Comment by davideprevosto** [comment]
> I assume you've tested this and it works as intended? No conflict with partials or anything?

We are using this PR on a production website and it is running well. At the moment we haven't catch any conflict.

> Would you be able to fix the remaining linting that happened on the file?

I fixed all the linting on my second commit. I hope I didn't make a mistake, it was my first time with phpcbf used for a PR. Sorry for any inconvenience.

**Comment by ryanemitchell** [comment]
I'm running this on local development server and is working well.  I'm happy to do any testing that may help get this merged in.  Thanks for this @davideprevosto

**Comment by davideprevosto** [comment]
> I'm running this on local development server and is working well. I'm happy to do any testing that may help get this merged in. Thanks for this @davideprevosto

Thank you for the feedback @ryanemitchell 
We are still using this change, also with acorn 2.0.6, without issues.

**Comment by pgooch** [comment]
Any chance we can get this reviewed and merged into master?

**Pull request merged**
